name: Build and publish
on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: sqlexec
  WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: .
  PS_SOURCE_URL: "https://raw.githubusercontent.com/jsorling/miscscripts/main/github/actions"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Set build info
      run: '& iex ((New-Object System.Net.WebClient).DownloadString("$env:PS_SOURCE_URL/buildinfo.ps1"))'
      shell: pwsh
    - name: Publish
      run: >
        dotnet publish
        src/sqlexecDevWeb/sqlexecDevWeb.csproj
        --configuration ${{ env.CONFIGURATION }}
        --output "${{ env.WEBAPP_PACKAGE_PATH }}"
        -p:PublishSingleFile=true
        --self-contained false
        --runtime linux-x64
        -p:DebugSymbols=false
        -p:DebugType=None
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.WEBAPP_PACKAGE_PATH }}
